### ISSUE TITLE
typos in README

### ISSUE THREAD

**Issue by storypixel** [cliftonc/express-mvc-bootstrap#1]
Thank you for creating such a helpful resource, seriously. This is hugely helping me get more into node.js. I found two minor typos in the readme:

type one:
- npm install express-mvc-bootsrap

(should be 'bootstrap'...)
- npm install express-mvc-bootstrap

typo two:
eb sever server.port=3000 <Runs server on different port>

(should be 'server')

eb server server.port=3000 <Runs server on different port>

**Comment by cliftonc** [comment]
No problem, glad it helps.  Typos all fixed!
