### ISSUE TITLE
Need a way to enable the node --debug

### ISSUE THREAD

**Issue by interlock** [cliftonc/express-mvc-bootstrap#2]
I've only been at this for a very short time, so perhaps there is a way. Looking over the eb.js code, it doesn't look like there is thou. In fact, this may not be possible at this time. If so, is there an alternate way to load up the app.js directly from 'node' so I can append the --debug flag?

**Comment by interlock** [comment]
I've submitted a simple patch to fix this. Yay me!

**Comment by cliftonc** [comment]
Thanks!
