### ISSUE TITLE
package dependency problem on npm 1.0+ 

### ISSUE THREAD

**Issue by ghost** [cliftonc/express-mvc-bootstrap#8]
With npm 1.0+  it separates packages to global and local.
If we install modules globally than they can not be found on require.
If we install modules locally than we can not use the *bin file ex. eb

Even if we install express-mvc-bootstrap both in local and in global
It still does not work. Because all the dependent packages will be installed under  express-mvc-bootstrap,
suck as cluster, express... etc.

Therefore I manually installed all the dependent packages locally to get express-mvc-bootstrap to work

**Comment by dreamerslab** [comment]
Added docs on readme.md
